### ISSUE TITLE
centos8两个脚本均报错，安装失败

### ISSUE THREAD

**Issue by yeming-jump** [sspanel-uim/Wiki#11]
报错如下：
 * ERROR: Failed to run install_centos_stable_deps()!!!
Writing Salt config...
sed: can't read /etc/salt/minion: No such file or directory
System require a reboot to complete the installation process, press Y to continue, or press any key else to exit this script.

**Comment by yeming-jump** [comment]
同时在面板也看不到成功连接

**Comment by Toxic-Cat** [comment]
這個是salt的安裝脚本有問題，稍後會把這個功能移除。

**Comment by Toxic-Cat** [comment]
Fixed.
