### ISSUE TITLE
安装教程修改建议

### ISSUE THREAD

**Issue by QASDJKL5** [sspanel-uim/Wiki#45]
我用的是AMD，ubuntu22.04，在“启动 php-fpm 服务并设置开机启动”这一步中，要把php-fpm改成php8.2-fpm，不知道其他平台会不会有这个问题

**Comment by M1Screw** [comment]
Fixed at https://github.com/sspanel-uim/Wiki/commit/7d49937e25b69d859e9f15849d3ed4702167e37e.
