### ISSUE TITLE
sudo -u www-data /usr/bin/php xcat ClientDownload 这行命令运行时提示权限不足

### ISSUE THREAD

**Issue by wietrade** [sspanel-uim/Wiki#48]
root@li-Virtual-Machine:/home/li/www/haod# sudo -u www-data /usr/bin/php xcat ClientDownload
PHP Warning:  require(/home/li/www/haod/app/predefine.php): Failed to open stream: Permission denied in /home/li/www/haod/xcat on line 8
PHP Fatal error:  Uncaught Error: Failed opening required '/home/li/www/haod/app/predefine.php' (include_path='.:/usr/share/php') in /home/li/www/haod/xcat:8
Stack trace:
#0 {main}
  thrown in /home/li/www/haod/xcat on line 8

**Comment by mocuishlelin** [comment]
需要整个目录属主改为 www-data：
chown -Rf www-data:www-data /home/li/www/
